# Configuration for World Para Powerlifting.

[options]
    require_manual_disambiguation = true

[rulesets.default]
	ruleset = ["FourthAttemptsMayLower"]
	date_range = ["0000-01-01", "9999-01-01"]

[divisions]
    open = {name="Open", min=0, max=999, equipment="Raw"}
    juniors = {name="Juniors", min=0, max=22.5, equipment="Raw"}
    groupa = {name="Group A", min=0, max=999, equipment="Raw"}
    groupb = {name="Group B", min=0, max=999, equipment="Raw"}
    groupc = {name="Group C", min=0, max=999, equipment="Raw"}
    lw = {name="Lightweight", min=0, max=999, equipment="Raw"}
    hw = {name="Heavyweight", min=0, max=999, equipment="Raw"}

	# Old divisions.
	paraplegic = {name="Paraplegic", min=0, max=999, equipment="Raw"}
	amputee = {name="Amputee", min=0, max=999, equipment="Raw"}

[weightclasses.default_M]
    classes = ["49","54","59","65","72","80","88","97","107","107+"]
    date_range = ["2013-01-01","9999-01-01"]
    sex = "M"

[weightclasses.default_F]
    classes = ["41","45","50","55","61","67","73","79","86","86+"]
    date_range = ["2013-01-01","9999-01-01"]
    sex = "F"

[weightclasses.old_M]
    classes = ["48","52","56","60","67.5","75","82.5","90","100","100+"]
    date_range = ["0000-01-01","2012-12-31"]
    sex = "M"

[weightclasses.old_F]
    classes = ["40","44","48","52","56","60","67.5","75","82.5","82.5+"]
    date_range = ["0000-01-01","2012-12-31"]
    sex = "F"

[exemptions]
	6401 = ["ExemptWeightClassConsistency"] # Very old weightclasses.
	6801 = ["ExemptWeightClassConsistency"] # Very old weightclasses.
	7201 = ["ExemptWeightClassConsistency"] # Very old weightclasses.
	7601 = ["ExemptWeightClassConsistency"] # Very old weightclasses.
	8001 = ["ExemptWeightClassConsistency"] # Very old weightclasses.
    8401 = ["ExemptWeightClassConsistency"]
    0301 = ["ExemptWeightClassConsistency"] # Guessed at weightclasses.
    0602 = ["ExemptWeightClassConsistency"] # No weightclasses used.
    0704 = ["ExemptWeightClassConsistency"] # No weightclasses used.
    0705 = ["ExemptWeightClassConsistency"] # Nonstandard weightclasses.
    0906 = ["ExemptWeightClassConsistency"] # No weightclasses used for women.
    1908 = ["ExemptWeightClassConsistency"] # Used old weightclasses.
