[divisions]
    open = {name = "Open", min = 0, max = 999}
    t1315 = {name ="Teen 13-15",min=14,max=15}
    t1617 = {name ="Teen 16-17",min=16,max=17}
    t1819 = {name ="Teen 18-19",min=18,max=19}
    j2023 = {name ="Juniors 20-23",min=20,max=23}

    masters_40_49 = {name = "Masters 40-49", min = 40, max = 49}
    masters_50_59 = {name = "Masters 50-59", min = 50, max = 59}
    masters_60_69 = {name = "Masters 60-69", min = 60, max = 69}
    masters_70_79 = {name = "Masters 70-79", min = 70, max = 79}
    masters_80p = {name = "Masters 80+", min = 80, max = 999}

[weightclasses.default_M]
    classes = ["52","56","60","67.5","75","82.5","90","100","110","125","140","140+"]
    date_range = ["1990-01-01", "9999-01-01"]
    sex = "M"

[weightclasses.default_F]
    classes = ["44","48","52","56","60","67.5","75","82.5","90","90+"]
    date_range = ["1990-01-01", "9999-01-01"]
    sex = "F"

[exemptions]
