[divisions]
    open = {name = "Open", min = 0, max = 999}
    youth = {name = "Youth", min = 5, max = 14} #Not a real division
    teen_15_19 = {name = "T15-19", min = 15, max = 19}
    junior = {name = "Junior", min = 20, max = 23}
    masters_40p = {name = "M40+", min = 40, max = 44}
    masters_45p = {name = "M45+", min = 45, max = 49}
    masters_50p = {name = "M50+", min = 50, max = 54}
    masters_55p = {name = "M55+", min = 55, max = 59}
    masters_60p = {name = "M60+", min = 60, max = 64}
    masters_65p = {name = "M65+", min = 65, max = 69}
    masters_70p = {name = "M70+", min = 70, max = 74}
    masters_75p = {name = "M75+", min = 75, max = 79}
    masters_80p = {name = "M80+", min = 80, max = 999}

[weightclasses.default_M]
    classes = ["52","56","60","67.5","75","82.5","90","100","110","125","140","140+"]
    date_range = ["1990-01-01", "9999-01-01"]
    sex = "M"

[weightclasses.default_F]
    classes = ["44","48","52","56","60","67.5","75","82.5","90","90+"]
    date_range = ["1990-01-01", "9999-01-01"]
    sex = "F"

[exemptions]
