[divisions]
    military = {name ="Military",min=0,max=999}

    ama_teen_14_15 = {name="Amateur Teen 14-15", min=14, max=15, tested="Yes"}
    ama_teen_16_17 = {name="Amateur Teen 16-17", min=16, max=17, tested="Yes"}
    ama_teen_18_19 = {name="Amateur Teen 18-19", min=18, max=19, tested="Yes"}
    ama_juniors = {name="Amateur Juniors 20-23", min=20, max=23, tested="Yes"}
    ama_open = {name="Amateur Open", min=0, max=999, tested="Yes"}
    ama_submasters = {name="Amateur Submasters 33-39", min=33, max=39, tested="Yes"}
    ama_masters_40_44 = {name="Amateur Masters 40-44", min=40, max=44, tested="Yes"}
    ama_masters_45_49 = {name="Amateur Masters 45-49", min=45, max=49, tested="Yes"}
    ama_masters_50_54 = {name="Amateur Masters 50-54", min=50, max=54, tested="Yes"}
    ama_masters_55_59 = {name="Amateur Masters 55-59", min=55, max=59, tested="Yes"}
    ama_masters_60_64 = {name="Amateur Masters 60-64", min=60, max=64, tested="Yes"}
    ama_masters_65_69 = {name="Amateur Masters 65-69", min=65, max=69, tested="Yes"}
    ama_masters_70_74 = {name="Amateur Masters 70-74", min=70, max=74, tested="Yes"}
    ama_masters_75_79 = {name="Amateur Masters 75-79", min=75, max=79, tested="Yes"}
    ama_masters_80p = {name="Amateur Masters 80+", min=80, max=999, tested="Yes"}
    ama_police = {name="Amateur Police", min=0, max=999, tested="Yes"}

    # Pro divisions.
    pro_teen_14_15 = {name="Pro Teen 14-15", min=14, max=15}
    pro_teen_16_17 = {name="Pro Teen 16-17", min=16, max=17}
    pro_teen_18_19 = {name="Pro Teen 18-19", min=18, max=19}
    pro_juniors = {name="Pro Juniors 20-23", min=20, max=23}
    pro_open = {name="Pro Open", min=0, max=999}
    pro_submasters = {name="Pro Submasters 33-39", min=33, max=39}
    pro_masters_40_44 = {name="Pro Masters 40-44", min=40, max=44}
    pro_masters_45_49 = {name="Pro Masters 45-49", min=45, max=49}
    pro_masters_50_54 = {name="Pro Masters 50-54", min=50, max=54}
    pro_masters_55_59 = {name="Pro Masters 55-59", min=55, max=59}
    pro_masters_60_64 = {name="Pro Masters 60-64", min=60, max=64}
    pro_masters_65_69 = {name="Pro Masters 65-69", min=65, max=69}
    pro_masters_70_74 = {name="Pro Masters 70-74", min=70, max=74}
    pro_masters_75_79 = {name="Pro Masters 75-79", min=75, max=79}
    pro_masters_80p = {name="Pro Masters 80+", min=80, max=999}

    pro_teen = {name="Pro Teen", min=13, max=19}
    ama_teen = {name="Amateur Teen", min=13, max=19, tested="Yes"}

[weightclasses.default_M]
    classes = ["60","70","80","90","100","110","120","140","140+"]
    date_range=["2011-01-01","9999-01-01"]
    sex = "M"

[weightclasses.default_F]
    classes = ["50","60","70","80","90","90+"]
    date_range=["1900-01-01","9999-01-01"]
    sex = "F"


[exemptions]
    1901 = ["ExemptWeightClassConsistency"] #130,130+ classes
